#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-httpuv
Version  : 1.3.3
Release  : 4
URL      : https://cran.r-project.org/src/contrib/httpuv_1.3.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/httpuv_1.3.3.tar.gz
Summary  : HTTP and WebSocket Server Library
Group    : Development/Tools
License  : GPL-3.0 MIT
Requires: R-httpuv-lib
Requires: R-Rcpp
BuildRequires : R-Rcpp
BuildRequires : clr-R-helpers

%description
# httpuv: HTTP and WebSocket server library for R
httpuv provides low-level socket and protocol support for handling
HTTP and WebSocket requests directly from within R. It is primarily intended
as a building block for other packages, rather than making it particularly
easy to create complete web applications using httpuv alone. httpuv is built
on top of the [libuv](https://github.com/joyent/libuv) and [http-parser](https://github.com/joyent/http-parser) C libraries, both of which were developed
by Joyent, Inc.

%package lib
Summary: lib components for the R-httpuv package.
Group: Libraries

%description lib
lib components for the R-httpuv package.


%prep
%setup -q -c -n httpuv

%build
export LANG=C

%install
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library httpuv
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library httpuv


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/httpuv/DESCRIPTION
/usr/lib64/R/library/httpuv/INDEX
/usr/lib64/R/library/httpuv/LICENSE
/usr/lib64/R/library/httpuv/Meta/Rd.rds
/usr/lib64/R/library/httpuv/Meta/demo.rds
/usr/lib64/R/library/httpuv/Meta/hsearch.rds
/usr/lib64/R/library/httpuv/Meta/links.rds
/usr/lib64/R/library/httpuv/Meta/nsInfo.rds
/usr/lib64/R/library/httpuv/Meta/package.rds
/usr/lib64/R/library/httpuv/NAMESPACE
/usr/lib64/R/library/httpuv/NEWS
/usr/lib64/R/library/httpuv/R/httpuv
/usr/lib64/R/library/httpuv/R/httpuv.rdb
/usr/lib64/R/library/httpuv/R/httpuv.rdx
/usr/lib64/R/library/httpuv/demo/daemon-echo.R
/usr/lib64/R/library/httpuv/demo/echo.R
/usr/lib64/R/library/httpuv/help/AnIndex
/usr/lib64/R/library/httpuv/help/aliases.rds
/usr/lib64/R/library/httpuv/help/httpuv.rdb
/usr/lib64/R/library/httpuv/help/httpuv.rdx
/usr/lib64/R/library/httpuv/help/paths.rds
/usr/lib64/R/library/httpuv/html/00Index.html
/usr/lib64/R/library/httpuv/html/R.css
/usr/lib64/R/library/httpuv/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/httpuv/libs/httpuv.so
